- job: PostmanTests
    steps:
    - script: |
       newman run "Regresssion Test Suite.postman_collection.json" -e "Production.postman_environment.json" --reporters cli,junit --reporter-junit-export Results\junitReport.xml        
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      displayName: 'Run API tests'
      continueOnError: true    
    - task: PublishTestResults@1
      displayName: 'Publish Test Results'
      inputs:
        testResultsFiles: '$(System.DefaultWorkingDirectory)\Results\*.xml'
  - job: SeleniumTests
    - script:  
        python selenium_tests.py    
      displayName: 'Run tests'
